//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNMIPSAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNNMIPSEntities : DbContext
    {
        public DNNMIPSEntities()
            : base("name=DNNMIPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Lookup_QPP_Measure_Type> tbl_Lookup_QPP_Measure_Type { get; set; }
        public virtual DbSet<tbl_Lookup_QPP_Measures> tbl_Lookup_QPP_Measures { get; set; }
        public virtual DbSet<tbl_Lookup_QPP_Modality> tbl_Lookup_QPP_Modality { get; set; }
        public virtual DbSet<tbl_Lookup_Registry> tbl_Lookup_Registry { get; set; }
        public virtual DbSet<tbl_Lookup_Specialty> tbl_Lookup_Specialty { get; set; }
        public virtual DbSet<tbl_Measure_To_QPP_Modality> tbl_Measure_To_QPP_Modality { get; set; }
        public virtual DbSet<vw_QPPMeasures_With_Modality> vw_QPPMeasures_With_Modality { get; set; }
        public virtual DbSet<Tbl_lookup_ImprovementActivities> Tbl_lookup_ImprovementActivities { get; set; }
        public virtual DbSet<Tbl_IA_Data> Tbl_IA_Data { get; set; }
    }
}
