//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNMIPSAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lookup_QPP_Measures
    {
        public int ID { get; set; }
        public string Measure_Num { get; set; }
        public string Measure_Title { get; set; }
        public string Measure_Description { get; set; }
        public string Measure_Type_Code { get; set; }
        public string Measure_Type_Modifier { get; set; }
        public string Measure_Priority { get; set; }
        public string Domain { get; set; }
        public string Cross_Cutting { get; set; }
        public string Specialty { get; set; }
        public string Registry { get; set; }
        public string Reporting_Method { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> CMS_Year { get; set; }
        public string Message { get; set; }
        public string Measure_URL { get; set; }
        public string Message2 { get; set; }
    }
}
