//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNMIPSAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Measure_To_QPP_Modality
    {
        public int Id { get; set; }
        public string Measure_Num { get; set; }
        public Nullable<int> Modality_Id { get; set; }
        public Nullable<int> CMS_Year { get; set; }
    }
}
