//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNMIPSAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IA_Data
    {
        public short ID { get; set; }
        public string ActivityID { get; set; }
        public string ActivityName { get; set; }
        public string ActivityDescription { get; set; }
        public short Subcategory { get; set; }
        public string Weighing { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Tbl_lookup_ImprovementActivities Tbl_lookup_ImprovementActivities { get; set; }
    }
}
